version: 2.1

orbs:
  architect: giantswarm/architect@2.7.0
workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: app-catalog
          context: "architect"
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cluster-api-bootstrap-provider-kubeadm"
          filters:
            tags:
              only: /^v.*/
